---
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    versioning-strategy: "lockfile-only"
    allow:
      - dependency-type: "all"

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    versioning-strategy: "lockfile-only"
    allow:
      - dependency-type: "all"
