- project:
    check:
      jobs:
        - tox-lint:
            override-checkout: master
        - tox-python37:
            override-checkout: master
        - tox-python38:
            override-checkout: master
        - tox-python39:
            override-checkout: master
        - simple-tox-docs:
            override-checkout: master
        - tox-diff-cover:
            override-checkout: master
