- project:
    check:
      jobs:
        - fi-tox-lint:
            override-checkout: master
            vars:
              dependencies:
                - libpq-devel
                - krb5-devel
        - fi-tox-python37:
            override-checkout: master
            vars:
              dependencies:
                - libpq-devel
                - krb5-devel
        - fi-tox-python38:
            override-checkout: master
            vars:
              dependencies:
                - libpq-devel
                - krb5-devel
        - fi-tox-python39:
            override-checkout: master
            vars:
              dependencies:
                - libpq-devel
                - krb5-devel
        - fi-tox-docs:
            override-checkout: master
            vars:
              dependencies:
                - libpq-devel
                - krb5-devel
                - python3-pydot
        - fi-tox-diff-cover:
            override-checkout: master
            vars:
              dependencies:
                - libpq-devel
                - krb5-devel
