# SPDX-FileCopyrightText: Contributors to the Fedora Project
#
# SPDX-License-Identifier: MIT

---
- hosts: all
  become: true
  become_method: sudo
  vars:
    ipa_hostname: ipa.tinystage.test
    ipsilon_hostname: ipsilon.tinystage.test
    fasjson_hostname: fasjson.tinystage.test

  roles:
    - ipa-client
    - cert
    - base
    - oidc-register
    - gss-proxy
    - database/server
    - database/client
    - backend
    - api
    - name: oidc-register
      redirect_url: https://{{ ansible_fqdn }}:5173/login/fedora
      dest: /home/vagrant/frontend_oidc.json
    - frontend
    - consumer
    - sender
    - redis
    - collectd
