---
- hosts: all
  become: true
  become_method: sudo
  roles:
    - ipa-client
    - cert
    - base
    - oidc-register
    - gss-proxy
    - database/server
    - database/client
    - backend
    - api
    - name: oidc-register
      redirect_url: https://{{ ansible_fqdn }}:5173/login/fedora
      dest: /home/vagrant/frontend_oidc.json
    - frontend
    - consumer
    - sender
    - redis
