/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/users/me": {
    /** Get Me */
    get: operations["get_me_api_v1_users_me_get"];
  };
  "/api/v1/users": {
    /** Get Users */
    get: operations["get_users_api_v1_users_get"];
  };
  "/api/v1/users/{username}/info": {
    /** Get User Info */
    get: operations["get_user_info_api_v1_users__username__info_get"];
  };
  "/api/v1/users/{username}/groups": {
    /** Get User Groups */
    get: operations["get_user_groups_api_v1_users__username__groups_get"];
  };
  "/api/v1/users/{username}/destinations": {
    /** Get User Destinations */
    get: operations["get_user_destinations_api_v1_users__username__destinations_get"];
  };
  "/api/v1/users/{username}/rules": {
    /** Get User Rules */
    get: operations["get_user_rules_api_v1_users__username__rules_get"];
    /** Create User Rule */
    post: operations["create_user_rule_api_v1_users__username__rules_post"];
  };
  "/api/v1/users/{username}/rules/{id}": {
    /** Get User Rule */
    get: operations["get_user_rule_api_v1_users__username__rules__id__get"];
    /** Edit User Rule */
    put: operations["edit_user_rule_api_v1_users__username__rules__id__put"];
    /** Delete User Rule */
    delete: operations["delete_user_rule_api_v1_users__username__rules__id__delete"];
  };
  "/api/v1/applications": {
    /** Get Applications */
    get: operations["get_applications_api_v1_applications_get"];
  };
  "/api/v1/artifacts/owned": {
    /** Get Owned Artifacts */
    get: operations["get_owned_artifacts_api_v1_artifacts_owned_get"];
  };
  "/api/v1/artifacts": {
    /** Get Artifacts */
    get: operations["get_artifacts_api_v1_artifacts_get"];
  };
  "/api/v1/rule-preview": {
    /** Preview Rule */
    post: operations["preview_rule_api_v1_rule_preview_post"];
  };
  "/api/v1/healthz/live": {
    /** Liveness Check */
    get: operations["liveness_check_api_v1_healthz_live_get"];
  };
  "/api/v1/healthz/ready": {
    /** Readiness Check */
    get: operations["readiness_check_api_v1_healthz_ready_get"];
  };
  "/api/v1/admin/rules": {
    /** Get Rules */
    get: operations["get_rules_api_v1_admin_rules_get"];
  };
  "/api/v1/admin/rules/{id}": {
    /** Patch Rule */
    patch: operations["patch_rule_api_v1_admin_rules__id__patch"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** Artifact */
    Artifact: {
      type: components["schemas"]["ArtifactType"];
      /** Name */
      name: string;
    };
    /** ArtifactOptionsGroup */
    ArtifactOptionsGroup: {
      /** Label */
      label: string;
      /** Options */
      options: (components["schemas"]["Option_Artifact_"])[];
    };
    /**
     * ArtifactType 
     * @description An enumeration. 
     * @enum {unknown}
     */
    ArtifactType: "rpms" | "containers" | "modules" | "flatpaks";
    /** ArtifactsFollowedTrackingRule */
    ArtifactsFollowedTrackingRule: {
      /**
       * Name 
       * @enum {string}
       */
      name: "artifacts-followed";
      /** Params */
      params: ({
          [key: string]: string | undefined;
        })[];
    };
    /** Destination */
    Destination: {
      /** Protocol */
      protocol: string;
      /** Address */
      address: string;
    };
    /** EmailNotification */
    EmailNotification: {
      /**
       * Protocol 
       * @enum {string}
       */
      protocol: "email";
      content: components["schemas"]["EmailNotificationContent"];
    };
    /** EmailNotificationContent */
    EmailNotificationContent: {
      headers: components["schemas"]["EmailNotificationHeaders"];
      /** Body */
      body: string;
    };
    /** EmailNotificationHeaders */
    EmailNotificationHeaders: {
      /** To */
      To: string;
      /** Subject */
      Subject: string;
    };
    /** Filters */
    Filters: {
      /**
       * Applications 
       * @default []
       */
      applications?: (string)[];
      /**
       * Severities 
       * @default []
       */
      severities?: (string)[];
      /** Topic */
      topic?: string;
      /**
       * My Actions 
       * @default false
       */
      my_actions?: boolean;
    };
    /** GenerationRule */
    GenerationRule: {
      /** Id */
      id?: number;
      /** Destinations */
      destinations: (components["schemas"]["Destination"])[];
      filters: components["schemas"]["Filters"];
    };
    /** GenerationRulePreview */
    GenerationRulePreview: {
      /** Id */
      id?: number;
      /**
       * Destinations 
       * @default []
       */
      destinations?: (components["schemas"]["Destination"])[];
      filters: components["schemas"]["Filters"];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: (components["schemas"]["ValidationError"])[];
    };
    /** IRCNotification */
    IRCNotification: {
      /**
       * Protocol 
       * @enum {string}
       */
      protocol: "irc";
      content: components["schemas"]["IRCNotificationContent"];
    };
    /** IRCNotificationContent */
    IRCNotificationContent: {
      /** To */
      to: string;
      /** Message */
      message: string;
    };
    /** ListParamTrackingRule */
    ListParamTrackingRule: {
      /**
       * Name 
       * @enum {string}
       */
      name: "artifacts-owned" | "artifacts-group-owned" | "users-followed";
      /** Params */
      params: (string)[];
    };
    /** MatrixNotification */
    MatrixNotification: {
      /**
       * Protocol 
       * @enum {string}
       */
      protocol: "matrix";
      content: components["schemas"]["MatrixNotificationContent"];
    };
    /** MatrixNotificationContent */
    MatrixNotificationContent: {
      /** To */
      to: string;
      /** Message */
      message: string;
    };
    /** NewRule */
    NewRule: {
      /** Name */
      name: string;
      /**
       * Disabled 
       * @default false
       */
      disabled?: boolean;
      /** Tracking Rule */
      tracking_rule: components["schemas"]["ListParamTrackingRule"] | components["schemas"]["NoParamTrackingRule"] | components["schemas"]["ArtifactsFollowedTrackingRule"];
      /** Generation Rules */
      generation_rules: (components["schemas"]["GenerationRule"])[];
    };
    /** NoParamTrackingRule */
    NoParamTrackingRule: {
      /**
       * Name 
       * @enum {string}
       */
      name: "related-events";
      /** Params */
      params?: string;
    };
    /** Notification */
    Notification: components["schemas"]["EmailNotification"] | components["schemas"]["IRCNotification"] | components["schemas"]["MatrixNotification"] | components["schemas"]["PreviewNotification"];
    /** Option[Artifact] */
    Option_Artifact_: {
      /** Label */
      label: string;
      value: components["schemas"]["Artifact"];
    };
    /** PreviewNotification */
    PreviewNotification: {
      /**
       * Protocol 
       * @enum {string}
       */
      protocol: "preview";
      content: components["schemas"]["PreviewNotificationContent"];
    };
    /** PreviewNotificationContent */
    PreviewNotificationContent: {
      /** Date */
      date: string;
      /** Topic */
      topic: string;
      /** Summary */
      summary: string;
      /** Priority */
      priority: number;
      /** Application */
      application: string;
      /** Author */
      author?: string;
    };
    /** Rule */
    Rule: {
      /** Name */
      name: string;
      /**
       * Disabled 
       * @default false
       */
      disabled?: boolean;
      /** Tracking Rule */
      tracking_rule: components["schemas"]["ListParamTrackingRule"] | components["schemas"]["NoParamTrackingRule"] | components["schemas"]["ArtifactsFollowedTrackingRule"];
      /** Generation Rules */
      generation_rules: (components["schemas"]["GenerationRule"])[];
      /** Id */
      id: number;
      user: components["schemas"]["User"];
      /**
       * Generated Last Week 
       * @default 0
       */
      generated_last_week?: number;
    };
    /** RulePatch */
    RulePatch: {
      /** Disabled */
      disabled?: boolean;
    };
    /** RulePreview */
    RulePreview: {
      /**
       * Name 
       * @default preview 
       * @enum {string}
       */
      name?: "preview";
      /**
       * Disabled 
       * @default false
       */
      disabled?: boolean;
      /** Tracking Rule */
      tracking_rule: components["schemas"]["ListParamTrackingRule"] | components["schemas"]["NoParamTrackingRule"] | components["schemas"]["ArtifactsFollowedTrackingRule"];
      /** Generation Rules */
      generation_rules: (components["schemas"]["GenerationRulePreview"])[];
    };
    /** User */
    User: {
      /** Id */
      id?: number;
      /** Name */
      name: string;
      /**
       * Is Admin 
       * @default false
       */
      is_admin?: boolean;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {

  get_me_api_v1_users_me_get: {
    /** Get Me */
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
  };
  get_users_api_v1_users_get: {
    /** Get Users */
    parameters?: {
      query?: {
        search?: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": (string)[];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_user_info_api_v1_users__username__info_get: {
    /** Get User Info */
    parameters: {
      path: {
        username: Record<string, never>;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_user_groups_api_v1_users__username__groups_get: {
    /** Get User Groups */
    parameters: {
      path: {
        username: Record<string, never>;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": (string)[];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_user_destinations_api_v1_users__username__destinations_get: {
    /** Get User Destinations */
    parameters: {
      path: {
        username: Record<string, never>;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": (components["schemas"]["Destination"])[];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_user_rules_api_v1_users__username__rules_get: {
    /** Get User Rules */
    parameters: {
      path: {
        username: Record<string, never>;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": (components["schemas"]["Rule"])[];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_user_rule_api_v1_users__username__rules_post: {
    /** Create User Rule */
    parameters: {
      path: {
        username: Record<string, never>;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewRule"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Rule"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_user_rule_api_v1_users__username__rules__id__get: {
    /** Get User Rule */
    parameters: {
      path: {
        username: string;
        id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Rule"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  edit_user_rule_api_v1_users__username__rules__id__put: {
    /** Edit User Rule */
    parameters: {
      path: {
        username: string;
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Rule"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Rule"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_user_rule_api_v1_users__username__rules__id__delete: {
    /** Delete User Rule */
    parameters: {
      path: {
        username: string;
        id: number;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_applications_api_v1_applications_get: {
    /** Get Applications */
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": (string)[];
        };
      };
    };
  };
  get_owned_artifacts_api_v1_artifacts_owned_get: {
    /** Get Owned Artifacts */
    parameters?: {
      query?: {
        users?: (string)[];
        groups?: (string)[];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": ({
              [key: string]: string | undefined;
            })[];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_artifacts_api_v1_artifacts_get: {
    /** Get Artifacts */
    parameters: {
      query: {
        name: string;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": (components["schemas"]["ArtifactOptionsGroup"])[];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  preview_rule_api_v1_rule_preview_post: {
    /** Preview Rule */
    requestBody: {
      content: {
        "application/json": components["schemas"]["RulePreview"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": (components["schemas"]["Notification"])[];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  liveness_check_api_v1_healthz_live_get: {
    /** Liveness Check */
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  readiness_check_api_v1_healthz_ready_get: {
    /** Readiness Check */
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  get_rules_api_v1_admin_rules_get: {
    /** Get Rules */
    parameters?: {
      query?: {
        disabled?: boolean;
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": (components["schemas"]["Rule"])[];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  patch_rule_api_v1_admin_rules__id__patch: {
    /** Patch Rule */
    parameters: {
      path: {
        id: number;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RulePatch"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        content: {
          "application/json": components["schemas"]["Rule"];
        };
      };
      /** @description Validation Error */
      422: {
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
