/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/users/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Me */
    get: operations["get_me_api_v1_users_me_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Users */
    get: operations["get_users_api_v1_users_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/{username}/info": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get User Info */
    get: operations["get_user_info_api_v1_users__username__info_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/{username}/groups": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get User Groups */
    get: operations["get_user_groups_api_v1_users__username__groups_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/{username}/destinations": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get User Destinations */
    get: operations["get_user_destinations_api_v1_users__username__destinations_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/{username}/rules": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get User Rules */
    get: operations["get_user_rules_api_v1_users__username__rules_get"];
    put?: never;
    /** Create User Rule */
    post: operations["create_user_rule_api_v1_users__username__rules_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/users/{username}/rules/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get User Rule */
    get: operations["get_user_rule_api_v1_users__username__rules__id__get"];
    /** Edit User Rule */
    put: operations["edit_user_rule_api_v1_users__username__rules__id__put"];
    post?: never;
    /** Delete User Rule */
    delete: operations["delete_user_rule_api_v1_users__username__rules__id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/applications": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Applications */
    get: operations["get_applications_api_v1_applications_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/artifacts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Artifacts
     * @description This handler queries artifacts from Pagure
     *
     *     Proxying Pagure queries lets the API cache results to reduce load on the
     *     backend service.
     *
     *     :param names: Name patterns of artifacts which should be returned
     *
     *     :param users: Names of users whose artifacts should be returned
     *
     *     :param groups: Names of groups whose artifacts should be returned
     */
    get: operations["get_artifacts_api_v1_artifacts_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/healthz/live": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness Check */
    get: operations["liveness_check_api_v1_healthz_live_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/healthz/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Readiness Check */
    get: operations["readiness_check_api_v1_healthz_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/rules": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Rules */
    get: operations["get_rules_api_v1_admin_rules_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Users */
    get: operations["get_users_api_v1_admin_users_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/admin/rules/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** Patch Rule */
    patch: operations["patch_rule_api_v1_admin_rules__id__patch"];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** Artifact */
    Artifact: {
      type: components["schemas"]["ArtifactType"];
      /** Name */
      name: string;
    };
    /**
     * ArtifactType
     * @enum {string}
     */
    ArtifactType: "rpms" | "containers" | "modules" | "flatpaks";
    /** ArtifactsFollowedTrackingRule */
    ArtifactsFollowedTrackingRule: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      name: "artifacts-followed";
      /** Params */
      params: {
        [key: string]: string;
      }[];
    };
    /** Destination */
    Destination: {
      /** Protocol */
      protocol: string;
      /** Address */
      address: string;
    };
    /** Filters */
    Filters: {
      /**
       * Applications
       * @default []
       */
      applications: string[];
      /**
       * Excluded Applications
       * @default []
       */
      excluded_applications: string[];
      /**
       * Severities
       * @default []
       */
      severities: string[];
      /** Topic */
      topic?: string | null;
      /**
       * My Actions
       * @default false
       */
      my_actions: boolean;
    };
    /** GenerationRule */
    GenerationRule: {
      /** Id */
      id?: number | null;
      /** Destinations */
      destinations: components["schemas"]["Destination"][];
      filters: components["schemas"]["Filters"];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** ListParamTrackingRule */
    ListParamTrackingRule: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      name: "artifacts-group-owned" | "artifacts-owned" | "users-followed";
      /** Params */
      params: string[];
    };
    /** NewRule */
    NewRule: {
      /** Name */
      name?: string | null;
      /**
       * Disabled
       * @default false
       */
      disabled: boolean;
      /** Tracking Rule */
      tracking_rule:
        | components["schemas"]["ListParamTrackingRule"]
        | components["schemas"]["NoParamTrackingRule"]
        | components["schemas"]["ArtifactsFollowedTrackingRule"];
      /** Generation Rules */
      generation_rules: components["schemas"]["GenerationRule"][];
    };
    /** NoParamTrackingRule */
    NoParamTrackingRule: {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      name: "related-events";
      /** Params */
      params?: string | null;
    };
    /** Rule */
    "Rule-Input": {
      /** Name */
      name?: string | null;
      /**
       * Disabled
       * @default false
       */
      disabled: boolean;
      /** Tracking Rule */
      tracking_rule:
        | components["schemas"]["ListParamTrackingRule"]
        | components["schemas"]["NoParamTrackingRule"]
        | components["schemas"]["ArtifactsFollowedTrackingRule"];
      /** Generation Rules */
      generation_rules: components["schemas"]["GenerationRule"][];
      /** Id */
      id: number;
      user: components["schemas"]["User"];
      /**
       * Generated Last Week
       * @default 0
       */
      generated_last_week: number;
    };
    /** Rule */
    "Rule-Output": {
      /** Name */
      name?: string | null;
      /**
       * Disabled
       * @default false
       */
      disabled: boolean;
      /** Tracking Rule */
      tracking_rule:
        | components["schemas"]["ListParamTrackingRule"]
        | components["schemas"]["NoParamTrackingRule"]
        | components["schemas"]["ArtifactsFollowedTrackingRule"];
      /** Generation Rules */
      generation_rules: components["schemas"]["GenerationRule"][];
      /** Id */
      id: number;
      user: components["schemas"]["User"];
      /**
       * Generated Last Week
       * @default 0
       */
      generated_last_week: number;
    };
    /** RulePatch */
    RulePatch: {
      /** Disabled */
      disabled?: boolean | null;
    };
    /** User */
    User: {
      /** Id */
      id?: number | null;
      /** Name */
      name: string;
      /**
       * Is Admin
       * @default false
       */
      is_admin: boolean;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_me_api_v1_users_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
  };
  get_users_api_v1_users_get: {
    parameters: {
      query?: {
        search?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string[];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_user_info_api_v1_users__username__info_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        username: unknown;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_user_groups_api_v1_users__username__groups_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        username: unknown;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string[];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_user_destinations_api_v1_users__username__destinations_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        username: unknown;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Destination"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_user_rules_api_v1_users__username__rules_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        username: unknown;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Rule-Output"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_user_rule_api_v1_users__username__rules_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        username: unknown;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["NewRule"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Rule-Output"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_user_rule_api_v1_users__username__rules__id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        username: string;
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Rule-Output"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  edit_user_rule_api_v1_users__username__rules__id__put: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        username: string;
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Rule-Input"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Rule-Output"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_user_rule_api_v1_users__username__rules__id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        username: string;
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_applications_api_v1_applications_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": string[];
        };
      };
    };
  };
  get_artifacts_api_v1_artifacts_get: {
    parameters: {
      query?: {
        names?: string[];
        users?: string[];
        groups?: string[];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Artifact"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  liveness_check_api_v1_healthz_live_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  readiness_check_api_v1_healthz_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  get_rules_api_v1_admin_rules_get: {
    parameters: {
      query?: {
        disabled?: boolean | null;
        username?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Rule-Output"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_users_api_v1_admin_users_get: {
    parameters: {
      query?: {
        search?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["User"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  patch_rule_api_v1_admin_rules__id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RulePatch"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Rule-Output"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
