"""Add presentation booleans.

Revision ID: 33082c0ecf3f
Revises: None
Create Date: 2014-06-09 13:45:28.859100

"""

# revision identifiers, used by Alembic.
revision = '33082c0ecf3f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('preferences', sa.Column('shorten_links', sa.Boolean(), default=False))
    op.add_column('preferences', sa.Column('triggered_by_links', sa.Boolean(), default=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('preferences', 'triggered_by_links')
    op.drop_column('preferences', 'shorten_links')
    ### end Alembic commands ###
