---
- name: Copy helper scripts for fmn-api
  copy:
    src: "{{item}}"
    dest: "/home/vagrant/.local/bin/"
    owner: vagrant
    group: vagrant
    mode: 0744
  loop:
    - fmn-api-logs
    - fmn-api-restart
    - fmn-api-start
    - fmn-api-status
    - fmn-api-stop

- name: Install the systemd unit files for the fmn-api service
  copy:
    src: fmn-api.service
    dest: /etc/systemd/system/fmn-api.service
    mode: 0644

- name: install the api with poetry
  command: poetry install
  become: yes
  become_user: vagrant
  args:
    chdir: /home/vagrant/fmn/

# - name: Determine poetry venv path
#   command: poetry env info --path
#   register: _poetry_venv_path
#   changed_when: False

# - name: Set poetry venv path fact
#   set_fact:
#     poetryvenvpath: "{{ _poetry_venv_path.stdout | trim }}"

- name: Register the API as an OIDC client with Ipsilon
  command:
    cmd: >
      oidc-register --debug --output-file /home/vagrant/api-oidc-secrets.json
      https://ipsilon.tinystage.test/idp/openidc/ https://fmn.tinystage.test/
    creates: /home/vagrant/api-oidc-secrets.json
  become: yes
  become_user: vagrant

- name: Read the OIDC credentials file
  slurp:
    src: /home/vagrant/api-oidc-secrets.json
  register: api_oidc_secrets_out

- name: Set OIDC client credentials
  set_fact:
    oidc_client_id: "{{ (api_oidc_secrets_out.content | b64decode | from_json).web.client_id }}"
    oidc_client_secret: >-
      {{ (api_oidc_secrets_out.content | b64decode | from_json).web.client_secret }}

- name: Install the configuration file
  template:
    src: fmn.cfg.j2
    dest: /home/vagrant/fmn/fmn.cfg
    mode: 0644

- name: Start the service using systemd
  systemd:
    state: started
    name: fmn-api
    daemon_reload: yes
    enabled: yes
