# SPDX-FileCopyrightText: Contributors to the Fedora Project
#
# SPDX-License-Identifier: MIT

---
- name: Copy helper scripts for fmn-api
  copy:
    src: "{{item}}"
    dest: "/home/vagrant/.local/bin/"
    owner: vagrant
    group: vagrant
    mode: 0744
  loop:
    - fmn-api-logs
    - fmn-api-restart
    - fmn-api-start
    - fmn-api-status
    - fmn-api-stop

- name: Install the systemd unit files for the fmn-api service
  copy:
    src: fmn-api.service
    dest: /etc/systemd/system/fmn-api.service
    mode: 0644

# - name: Determine poetry venv path
#   command: poetry env info --path
#   register: _poetry_venv_path
#   changed_when: False

# - name: Set poetry venv path fact
#   set_fact:
#     poetryvenvpath: "{{ _poetry_venv_path.stdout | trim }}"

# The configuration file is installed in the `backend` role.

- name: Start the service using systemd
  systemd:
    state: started
    name: fmn-api
    daemon_reload: yes
    enabled: yes
