export const msProps = [
  "placeholder",
  "mode",
  "closeOnSelect",
  "filterResults",
  "resolveOnLoad",
  "minChars",
  "delay",
  "groups",
  "groupHideEmpty",
  "groupSelect",
  "searchable",
  "valueProp",
  "object",
  "class",
  "classes",
];
