from fmn.rules.anitya import *
from fmn.rules.ansible import *
from fmn.rules.askbot import *
from fmn.rules.autocloud import *
from fmn.rules.bodhi import *
from fmn.rules.bugzilla import *
from fmn.rules.buildsys import *
from fmn.rules.compose import *
from fmn.rules.coprs import *
from fmn.rules.faf import *
from fmn.rules.fas import *
from fmn.rules.fedbadges import *
from fmn.rules.fedimg import *
from fmn.rules.fedocal import *
from fmn.rules.fedora_elections import *
from fmn.rules.fedoratagger import *
from fmn.rules.fmn_notifications import *
from fmn.rules.generic import *
from fmn.rules.github import *
from fmn.rules.git import *
from fmn.rules.hotness import *
from fmn.rules.infragit import *
from fmn.rules.jenkins import *
from fmn.rules.kerneltest import *
from fmn.rules.koschei import *
from fmn.rules.logger import *
from fmn.rules.mailman import *
from fmn.rules.mdapi import *
from fmn.rules.meetbot import *
from fmn.rules.nagios import *
from fmn.rules.nuancier import *
from fmn.rules.pagure import *
from fmn.rules.pkgdb import *
from fmn.rules.planet import *
from fmn.rules.summershum import *
from fmn.rules.taskotron import *
from fmn.rules.trac import *
from fmn.rules.wiki import *
